In [13]:
import pandas as pd

from google.colab import files
files.upload()

Saving HKRE0_Nairobi_-_Doonholm.csv to HKRE0_Nairobi_-_Doonholm.csv

{'HKRE0_Nairobi_-_Doonholm.csv': b'time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun\r\n2015-01-27,21.2,14.0,29.0,,,,11.8,,,\r\n2015-01-28,21.6,,,,,,15.1,,,\r\n2015-01-29,21.6,15.0,28.0,,,,12.9,,,\r\n2015-01-30,22.1,,,,,,15.5,,,\r\n2015-02-01,22.5,,,,,,15.4,,,\r\n2015-02-02,22.2,,,,,,13.6,,,\r\n2015-02-03,,,,,,,16.0,,,\r\n2015-02-04,21.4,,,,,,19.5,,,\r\n2015-02-05,22.0,,,,,,16.8,,,\r\n2015-02-07,22.3,,,,,,16.1,,,\r\n2015-02-08,21.3,,,,,,15.3,,,\r\n2015-02-09,22.0,,,,,,17.0,,,\r\n2015-02-10,21.8,16.0,28.0,,,,22.3,,,\r\n2015-02-11,22.2,,,,,,12.9,,,\r\n2015-02-12,22.7,,,,,,11.3,,,\r\n2015-02-13,23.6,17.0,30.0,,,,12.6,,,\r\n2015-02-14,23.1,,,,,,11.6,,,\r\n2015-02-15,21.0,19.0,24.0,,,,11.6,,,\r\n2015-02-16,21.6,18.0,28.0,,,,7.5,,,\r\n2015-02-17,20.6,,,,,,14.1,,,\r\n2015-02-18,22.1,18.0,27.0,,,,11.9,,,\r\n2015-02-19,22.0,17.0,27.0,,,,13.8,,,\r\n2015-02-20,21.8,18.0,27.0,,,,16.1,,,\r\n2015-02-21,22.8,18.0,29.0,,,,13.9,,,\r\n2015-02-22,22.4,,,,,,13.6,,,\r\n2015-02-23,21.8,16.0,28.0,,,,12.7,,,\r\n2015-02-24,22.4,15.0,29.0,,,,12.1,,,\r\n2015-02-27,22.9,,,,,,16.1,,,\r\n2015-02-28,22.8,,,,,,13.5,,,\r\n2015-03-03,21.6,15.0,28.0,,,,15.6,,,\r\n2015-03-06,22.3,,,,,,13.0,,,\r\n2015-03-07,22.5,,,,,,17.1,,,\r\n2015-03-08,22.4,,,,,,15.5,,,\r\n2015-03-11,21.9,,,,,,15.3,,,\r\n2015-03-12,22.1,15.0,28.0,,,,16.5,,,\r\n2015-03-13,21.6,,,,,,20.2,,,\r\n2015-03-16,22.2,16.0,28.0,,,,21.4,,,\r\n2015-03-19,22.3,17.0,29.0,,,,18.9,,,\r\n2015-03-25,21.2,18.0,27.0,,,,18.5,,,\r\n2015-03-28,20.7,,,,,,17.6,,,\r\n2015-03-29,21.3,18.0,27.0,,,,15.5,,,\r\n2015-04-01,22.4,18.0,28.0,,,,12.0,,,\r\n2015-04-04,19.8,,,,,,12.7,,,\r\n2015-04-05,20.6,16.0,27.0,,,,10.7,,,\r\n2015-04-08,22.4,18.0,29.0,,,,9.6,,,\r\n2015-04-09,20.4,,,,,,10.4,,,\r\n2015-04-16,21.8,18.0,26.0,,,,10.9,,,\r\n2015-04-17,18.8,,,,,,7.4,,,\r\n2015-04-18,20.1,,,,,,5.1,,,\r\n2015-04-21,21.0,17.0,26.0,,,,13.1,,,\r\n2015-04-24,20.5,,,,,,10.1,,,\r\n2015-04-25,20.8,,,,,,10.1,,,\r\n2015-04-26,19.7,16.0,27.0,,,,10.5,,,\r\n2015-04-29,19.6,16.0,25.0,,,,8.9,,,\r\n2015-05-07,20.4,,,,,,11.1,,,\r\n2015-05-10,20.8,,,,,,10.5,,,\r\n2015-05-11,20.4,,,,,,11.4,,,\r\n2015-05-22,19.9,,,,,,10.4,,,\r\n2015-05-23,20.0,,,,,,7.4,,,\r\n2015-05-29,,,,,,,7.4,,,\r\n2015-06-05,20.2,16.0,26.0,,,,5.7,,,\r\n2015-06-10,17.9,12.0,24.0,,,,5.6,,,\r\n2015-06-11,19.6,,,,,,,,,\r\n2015-06-12,18.5,,,,,,4.5,,,\r\n2015-06-13,18.0,14.0,23.0,,,,5.1,,,\r\n2015-06-14,19.3,,,,,,6.8,,,\r\n2015-06-15,20.4,,,,,,4.1,,,\r\n2025-07-14,18.9,13.2,24.1,0.7,,,9.2,,1019.3,\r\n2025-07-15,18.7,13.1,24.0,0.2,,,8.3,,1018.4,\r\n2025-07-16,18.9,13.9,23.8,0.7,,,8.0,,1018.0,\r\n2025-07-17,18.8,14.2,24.2,0.8,,,7.5,,1018.9,\r\n2025-07-18,19.2,15.3,23.9,0.9,,,8.6,,1019.5,\r\n2025-07-19,19.6,15.3,25.2,1.6,,,10.4,,1018.3,\r\n2025-07-20,18.2,12.5,25.0,0.0,,,10.2,,1016.8,\r\n2025-07-21,18.0,11.9,25.3,0.0,,,9.7,,1016.4,\r\n2025-07-22,17.7,12.9,24.1,0.0,,,10.3,,1018.0,\r\n2025-07-23,17.0,13.4,21.2,0.3,,,8.3,,1018.9,\r\n2025-07-24,18.2,12.0,25.6,0.0,,,9.7,,1017.6,\r\n2025-07-25,19.7,13.3,27.6,0.0,,,11.0,,1017.2,\r\n2025-07-26,19.2,12.4,26.6,0.0,,,10.0,,1018.2,\r\n2025-07-27,18.9,12.1,26.7,0.0,,,8.8,,1019.0,\r\n2025-07-28,18.5,12.0,26.4,0.0,,,11.4,,1019.6,\r\n2025-07-29,18.4,14.3,24.4,0.3,,,10.3,,1020.3,\r\n2025-07-30,18.7,13.2,27.5,0.0,,,11.8,,1020.8,\r\n2025-07-31,19.9,14.9,28.5,0.0,,,11.0,,1019.5,\r\n2025-08-01,19.0,14.9,24.5,0.0,,,9.1,,1018.6,\r\n2025-08-02,18.7,12.6,24.6,0.0,,,9.9,,1017.7,\r\n2025-08-03,18.3,13.1,23.7,0.0,,,11.3,,1018.0,\r\n2025-08-04,18.0,12.1,24.8,0.0,,,8.9,,1018.6,\r\n2025-08-05,17.9,12.7,23.7,0.0,,,10.0,,1018.4,\r\n2025-08-06,18.9,11.9,26.9,0.2,,,9.9,,1016.9,\r\n2025-08-07,19.1,15.5,27.1,5.3,,,8.1,,1015.4,\r\n2025-08-08,17.8,13.2,25.2,6.4,,,9.8,,1015.8,\r\n2025-08-09,17.2,14.7,20.8,0.3,,,7.8,,1017.6,\r\n2025-08-10,17.6,12.2,22.1,0.2,,,8.2,,1017.4,\r\n2025-08-11,17.2,12.6,22.5,0.1,,,8.6,,1017.3,\r\n2025-08-12,17.3,14.5,20.5,0.3,,,9.1,,1017.6,\r\n2025-08-13,18.7,12.6,24.2,0.2,,,9.0,,1016.9,\r\n2025-08-14,18.8,12.3,24.8,0.3,,,9.3,,1017.5,\r\n2025-08-15,19.4,14.7,24.9,0.3,,,8.2,,1017.0,\r\n2025-08-16,19.0,15.6,25.4,6.2,,,7.9,,1015.6,\r\n2025-08-17,17.9,15.1,22.5,8.4,,,7.0,,1016.2,\r\n2025-08-18,16.9,15.3,20.2,16.4,,,8.1,,1017.9,\r\n2025-08-19,17.2,15.3,20.2,5.1,,,9.9,,1018.0,\r\n2025-08-20,18.0,13.1,24.1,0.3,,,10.8,,1016.5,\r\n2025-08-21,17.4,14.2,20.9,0.4,,,10.0,,1016.9,\r\n2025-08-22,18.1,12.8,23.6,0.0,,,10.2,,1016.4,\r\n2025-08-23,16.5,13.7,19.3,0.0,,,8.8,,1017.4,\r\n2025-08-24,17.6,11.9,23.2,0.2,,,11.1,,1017.5,\r\n2025-08-25,18.4,14.7,22.9,6.4,,,10.5,,1018.6,\r\n2025-08-26,18.8,13.4,24.0,0.7,,,8.9,,1019.2,\r\n2025-08-27,19.4,14.3,26.6,0.0,,,10.1,,1018.3,\r\n2025-08-30,19.3,14.4,25.9,0.0,,,11.8,,1018.8,\r\n2025-08-31,19.0,,,,,,10.4,,1018.4,\r\n2025-09-02,19.7,12.1,27.8,0.0,,,11.1,,1016.6,\r\n2025-09-03,19.7,12.3,28.1,0.0,,,10.5,,1016.6,\r\n2025-09-12,19.9,12.8,27.4,0.0,,,10.1,,1017.0,\r\n2025-09-13,20.0,13.0,27.6,0.0,,,9.5,,1016.6,\r\n2025-09-14,20.4,13.6,29.1,0.8,,,9.4,,1015.8,\r\n2025-09-15,19.7,13.9,28.1,10.4,,,9.7,,1015.5,\r\n2025-09-16,19.5,13.8,26.7,2.5,,,10.0,,1015.5,\r\n2025-09-17,20.6,13.8,28.1,0.0,,,11.3,,1015.0,\r\n2025-09-18,20.0,16.4,26.3,3.7,,,12.8,,1016.3,\r\n2025-09-19,21.1,15.9,27.9,1.4,,,14.4,,1016.3,\r\n2025-09-20,20.2,12.9,28.2,0.0,,,11.2,,1017.1,\r\n2025-09-21,20.3,14.7,25.8,0.2,,,11.7,,1016.5,\r\n2025-09-22,20.2,13.4,26.7,0.3,,,12.6,,1017.0,\r\n2025-09-23,20.6,15.8,27.0,1.2,,,13.3,,1018.2,\r\n2025-09-24,20.0,12.5,27.1,0.0,,,9.9,,1017.7,\r\n2025-09-25,20.7,13.5,28.7,1.0,,,9.1,,1016.7,\r\n2025-09-26,21.1,15.2,28.8,0.2,,,8.6,,1016.0,\r\n2025-09-27,20.3,14.6,27.7,2.4,,,10.1,,1016.0,\r\n2025-09-28,20.8,14.0,28.0,0.4,,,10.5,,1016.5,\r\n2025-09-29,21.1,14.7,30.0,0.2,,,10.1,,1015.5,\r\n2025-09-30,21.0,14.7,29.4,0.0,,,10.6,,1014.7,\r\n2025-10-01,22.1,13.7,30.8,0.0,,,10.4,,1014.0,\r\n2025-10-02,21.5,13.9,29.0,0.0,,,10.4,,1013.8,\r\n2025-10-03,20.8,15.3,28.7,1.5,,,10.9,,1015.2,\r\n2025-10-04,19.2,16.0,25.6,19.2,,,10.2,,1016.8,\r\n2025-10-05,19.3,16.1,25.1,1.2,,,9.6,,1016.2,\r\n2025-10-06,19.1,14.1,25.0,1.5,,,11.9,,1016.7,\r\n2025-10-07,19.1,14.7,26.0,6.7,,,13.4,,1017.5,\r\n2025-10-08,19.1,15.5,25.1,3.6,,,13.7,,1017.4,\r\n2025-10-09,19.4,15.0,25.8,1.1,,,13.2,,1017.8,\r\n2025-10-10,19.5,14.6,25.7,2.9,,,12.1,,1017.2,\r\n2025-10-11,20.5,15.1,27.9,0.0,,,11.5,,1014.9,\r\n2025-10-12,20.4,13.8,27.2,0.1,,,11.5,,1014.4,\r\n2025-10-13,21.3,15.7,28.0,0.0,,,12.3,,1014.6,\r\n2025-10-14,20.6,15.6,26.8,0.0,,,11.6,,1015.8,\r\n2025-10-15,20.5,15.5,27.6,1.3,,,8.9,,1014.6,\r\n2025-10-16,20.5,16.3,27.0,2.9,,,9.4,,1014.3,\r\n2025-10-17,19.8,15.7,26.2,4.8,,,12.0,,1015.3,\r\n2025-10-18,19.7,15.0,25.6,0.2,,,10.9,,1016.4,\r\n2025-10-19,20.3,14.5,27.5,0.0,,,10.2,,1015.4,\r\n2025-10-20,20.9,12.8,28.7,0.0,,,11.2,,1013.9,\r\n2025-10-21,21.9,14.5,28.8,0.0,,,10.2,,1013.9,\r\n2025-10-22,20.2,15.4,27.2,0.4,,,10.3,,1016.1,\r\n2025-10-23,20.1,16.1,26.0,2.1,,,11.3,,1016.1,\r\n2025-10-24,19.3,16.3,23.8,8.7,,,10.3,,1016.3,\r\n2025-10-25,19.6,16.2,26.3,12.5,,,9.2,,1015.6,\r\n2025-10-26,20.6,15.3,27.0,0.3,,,9.1,,1014.6,\r\n2025-10-27,20.3,15.3,26.8,1.0,,,9.8,,1014.6,\r\n2025-10-28,19.5,15.5,25.5,13.1,,,9.9,,1015.4,\r\n2025-10-29,18.6,17.1,22.9,30.6,,,8.9,,1015.5,\r\n'}

In [15]:
import pandas as pd
df = pd.read_csv('HKRE0_Nairobi_-_Doonholm.csv')

In [16]:
df.shape

(164, 11)

In [17]:
# View the first few rows
df.head()

# Check column names and data types
df.info()

# Summary statistics
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    164 non-null    object
 1   tavg    162 non-null    float64
 2   tmin    124 non-null    float64
 3   tmax    124 non-null    float64
 4   prcp    96 non-null     float64
 5   snow    0 non-null      float64
 6   wdir    0 non-null      float64
 7   wspd    163 non-null    float64
 8   wpgt    0 non-null      float64
 9   pres    97 non-null     float64
 10  tsun    0 non-null      float64
dtypes: float64(10), object(1)
memory usage: 14.2+ KB

,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
count,162.000000,124.000000,124.000000,96.000000,0.0,0.0,163.000000,0.0,97.000000,0.0
mean,20.109259,14.665323,26.075000,2.120833,NaN,NaN,11.209816,NaN,1016.850515,NaN
std,1.553590,1.694517,2.308296,4.643885,NaN,NaN,3.118210,NaN,1.531008,NaN
min,16.500000,11.900000,19.300000,0.000000,NaN,NaN,4.100000,NaN,1013.800000,NaN
25%,19.000000,13.275000,24.575000,0.000000,NaN,NaN,9.400000,NaN,1015.800000,NaN
50%,20.150000,14.700000,26.600000,0.300000,NaN,NaN,10.500000,NaN,1016.800000,NaN
75%,21.300000,15.725000,27.925000,1.500000,NaN,NaN,12.650000,NaN,1018.000000,NaN
max,23.600000,19.000000,30.800000,30.600000,NaN,NaN,22.300000,NaN,1020.800000,NaN

In [18]:
# Check for missing values
df.isnull().sum()

time      0
tavg      2
tmin     40
tmax     40
prcp     68
snow    164
wdir    164
wspd      1
wpgt    164
pres     67
tsun    164
dtype: int64

In [19]:
# Dropping the columns that are completely empty
df = df.drop(columns=['snow', 'wdir', 'wpgt', 'tsun'])

In [20]:
df_cleaned = df.copy()

# First forward-fill (ffill), then backward-fill (bfill)
df_cleaned = df_cleaned.ffill().bfill()

In [21]:
# Verify cleaning
df_cleaned.isnull().sum()

time    0
tavg    0
tmin    0
tmax    0
prcp    0
wspd    0
pres    0
dtype: int64

In [22]:
df_cleaned.head()

         time  tavg  tmin  tmax  prcp  wspd    pres
0  2015-01-27  21.2  14.0  29.0   0.7  11.8  1019.3
1  2015-01-28  21.6  14.0  29.0   0.7  15.1  1019.3
2  2015-01-29  21.6  15.0  28.0   0.7  12.9  1019.3
3  2015-01-30  22.1  15.0  28.0   0.7  15.5  1019.3
4  2015-02-01  22.5  15.0  28.0   0.7  15.4  1019.3

In [23]:
df = df.round(1)

In [24]:
# Downloading the cleaned csv
df_cleaned.to_csv('HKRE0_Nairobi_-_Doonholm_cleaned.csv', index=False)